#!/usr/bin/env bash
# Setup InfraSafe data generator on demo server.
# Run: sudo bash setup-generator.sh
set -euo pipefail

PROJ=/home/infrasafe/infrasafe
COMPOSE_FILE=docker-compose.generator.yml
TS=$(date +%Y%m%d-%H%M%S)
BACKUP_DIR="/home/infrasafe/deploy-backups/$TS"
PG_CONTAINER=infrasafe-postgres-1
APP_CONTAINER=infrasafe-app-1
DB_USER=infrasafe_app
DB_NAME=infrasafe

if [ "$EUID" -ne 0 ]; then
    echo "ERROR: must run as root"
    exit 1
fi

mkdir -p "$BACKUP_DIR"

echo "============================================================"
echo "Setup data generator — $(date)"
echo "============================================================"

# ============================================================
# 1) Create service user 'generator' in DB
# ============================================================
echo ""
echo "=== 1. Create service user 'generator' ==="

GEN_PASSWORD=$(openssl rand -base64 24 | tr -d '+/=' | head -c 20)
echo "  generated password: $GEN_PASSWORD"

# bcrypt hash via the app container (uses app's bcrypt module)
GEN_HASH=$(docker exec "$APP_CONTAINER" node -e "console.log(require('bcrypt').hashSync('$GEN_PASSWORD', 10))" | tr -d '\r\n')
echo "  bcrypt hash length: ${#GEN_HASH}"

# users.username has no UNIQUE constraint (only email does), so DELETE + INSERT
# is simpler and more predictable than ON CONFLICT.
docker exec -i "$PG_CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -v ON_ERROR_STOP=1 <<SQL
DELETE FROM account_lockout WHERE login = 'generator';
DELETE FROM users WHERE username = 'generator' OR email = 'generator@infrasafe.local';
INSERT INTO users (username, email, password_hash, role, active, is_active, totp_enabled, password_changed_at)
VALUES ('generator', 'generator@infrasafe.local', '$GEN_HASH', 'user', true, true, false, NOW());
SQL
echo ""
echo "  verify user:"
docker exec "$PG_CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -At -c \
    "SELECT username, role, totp_enabled, length(password_hash) FROM users WHERE username = 'generator';"

# ============================================================
# 2) Create generator/.env
# ============================================================
echo ""
echo "=== 2. Write generator/.env ==="

cat > "$PROJ/generator/.env" <<EOF
# Auto-generated by setup-generator.sh on $(date -Iseconds)
PORT=8081
API_BASE_URL=http://app:3000/api
API_USERNAME=generator
API_PASSWORD=$GEN_PASSWORD
GENERATOR_CRON=*/5 * * * *
EOF
chown infrasafe:infrasafe "$PROJ/generator/.env"
chmod 600 "$PROJ/generator/.env"
echo "  $PROJ/generator/.env (mode 600)"

# Save copy of password to backup dir for emergency
echo "$GEN_PASSWORD" > "$BACKUP_DIR/generator-password.txt"
chmod 600 "$BACKUP_DIR/generator-password.txt"
chown infrasafe:infrasafe "$BACKUP_DIR/generator-password.txt"
echo "  password backup: $BACKUP_DIR/generator-password.txt"

# ============================================================
# 3) Patch generator compose: bind port to 127.0.0.1
# ============================================================
echo ""
echo "=== 3. Bind generator to 127.0.0.1 in compose ==="
cp -p "$PROJ/$COMPOSE_FILE" "$BACKUP_DIR/$COMPOSE_FILE.bak"
sed -i 's|- "8081:8081"|- "127.0.0.1:8081:8081"|' "$PROJ/$COMPOSE_FILE"
grep -n "ports:\|8081" "$PROJ/$COMPOSE_FILE" | sed 's/^/  /'

# ============================================================
# 4) Build + up
# ============================================================
echo ""
echo "=== 4. docker compose up generator ==="
sudo -u infrasafe -H bash <<EOSU
set -e
cd $PROJ
docker compose -f $COMPOSE_FILE up -d --build
EOSU

echo "  waiting 8s..."
sleep 8

# ============================================================
# 5) Verify
# ============================================================
echo ""
echo "=== 5. Verify ==="
echo ""
echo "  container:"
docker ps --filter name=generator --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | sed 's/^/    /'
echo ""
echo "  /health:"
curl -sf -m 5 http://127.0.0.1:8081/health 2>&1 | sed 's/^/    /' || echo "    FAILED"
echo ""
echo "  /api/ranges (empty config expected):"
curl -sf -m 5 http://127.0.0.1:8081/api/ranges 2>&1 | head -c 200 | sed 's/^/    /' || echo "    FAILED"
echo ""
echo "  generator login attempt (from inside container, against app):"
docker logs --tail 30 \$(docker ps --filter name=generator -q) 2>&1 | grep -E "apiClient|login|токен|metrics" | tail -10 | sed 's/^/    /' || true
echo ""
echo "  trigger one run manually:"
curl -sf -m 10 -X POST http://127.0.0.1:8081/api/run 2>&1 | head -c 300 | sed 's/^/    /' || echo "    (run endpoint may differ)"

echo ""
echo "============================================================"
echo "DONE — $(date)"
echo "============================================================"
echo ""
echo "Generator credentials:"
echo "  username: generator"
echo "  password: $GEN_PASSWORD  (also saved to $BACKUP_DIR/generator-password.txt)"
echo ""
echo "Access UI via SSH tunnel:"
echo "  ssh -p 32323 -N -L 8081:127.0.0.1:8081 infrasafe@95.46.96.105"
echo "  then http://localhost:8081/ in browser"
echo ""
echo "Generator schedule: */5 * * * * (every 5 min)"
echo "Container logs:    docker logs -f \$(docker ps --filter name=generator -q)"
echo ""
