const db = require('../config/database');
const logger = require('../utils/logger');

// RFC 4122 canonical form: 8-4-4-4-12 lowercase hex (case-insensitive in regex
// because pg accepts mixed case). Used to guard findByIdempotencyKey against
// non-uuid input — see hotfix note in that method.
const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

class AlertRequestMap {
    static async findByAlertId(alertId) {
        try {
            const result = await db.query(
                'SELECT * FROM alert_request_map WHERE infrasafe_alert_id = $1 ORDER BY created_at',
                [alertId]
            );
            return result.rows;
        } catch (error) {
            logger.error(`AlertRequestMap.findByAlertId error: ${error.message}`);
            throw error;
        }
    }

    static async create(data) {
        try {
            const { infrasafe_alert_id, building_external_id, idempotency_key, status = 'pending' } = data;
            const result = await db.query(
                `INSERT INTO alert_request_map
                 (infrasafe_alert_id, building_external_id, idempotency_key, status, created_at, updated_at)
                 VALUES ($1, $2, $3, $4, NOW(), NOW())
                 RETURNING *`,
                [infrasafe_alert_id, building_external_id, idempotency_key, status]
            );
            return result.rows[0];
        } catch (error) {
            if (error.code === '23505') {
                logger.warn('AlertRequestMap.create: duplicate alert+building pair');
                return null;
            }
            logger.error(`AlertRequestMap.create error: ${error.message}`);
            throw error;
        }
    }

    static async findByAlertAndBuilding(alertId, buildingExternalId) {
        try {
            const result = await db.query(
                'SELECT * FROM alert_request_map WHERE infrasafe_alert_id = $1 AND building_external_id = $2',
                [alertId, buildingExternalId]
            );
            return result.rows[0] || null;
        } catch (error) {
            logger.error(`AlertRequestMap.findByAlertAndBuilding error: ${error.message}`);
            throw error;
        }
    }

    static async markSent(id, requestNumber) {
        try {
            const result = await db.query(
                `UPDATE alert_request_map SET status = $1, uk_request_number = $2, updated_at = NOW()
                 WHERE id = $3 RETURNING *`,
                ['sent', requestNumber, id]
            );
            return result.rows[0] || null;
        } catch (error) {
            logger.error(`AlertRequestMap.markSent error: ${error.message}`);
            throw error;
        }
    }

    static async findByIdempotencyKey(idempotencyKey) {
        // [hotfix 2026-05-24] idempotency_key column is uuid type. Postgres
        // rejects non-uuid strings with "invalid input syntax for type uuid"
        // BEFORE the WHERE clause runs, which used to crash handleRequestWebhook
        // when UK callbacks carried arbitrary source_event_id values
        // (anything not generated by our own crypto.randomUUID() — synthetic
        // tests, manual UK injection, future schema migrations). Treat
        // non-uuid as "not found" so the receiver falls through to its
        // existing "log only" path instead of returning a 500.
        if (typeof idempotencyKey !== 'string' || !UUID_REGEX.test(idempotencyKey)) {
            return null;
        }
        try {
            const result = await db.query(
                'SELECT * FROM alert_request_map WHERE idempotency_key = $1',
                [idempotencyKey]
            );
            return result.rows[0] || null;
        } catch (error) {
            logger.error(`AlertRequestMap.findByIdempotencyKey error: ${error.message}`);
            throw error;
        }
    }

    static async findByRequestNumber(requestNumber) {
        try {
            const result = await db.query(
                'SELECT * FROM alert_request_map WHERE uk_request_number = $1',
                [requestNumber]
            );
            return result.rows[0] || null;
        } catch (error) {
            logger.error(`AlertRequestMap.findByRequestNumber error: ${error.message}`);
            throw error;
        }
    }

    static async updateStatus(id, status) {
        const VALID_STATUSES = ['pending', 'active', 'sent', 'resolved', 'cancelled'];
        if (!VALID_STATUSES.includes(status)) {
            throw new Error(`AlertRequestMap.updateStatus: invalid status '${status}'`);
        }
        try {
            const result = await db.query(
                'UPDATE alert_request_map SET status = $1, updated_at = NOW() WHERE id = $2 RETURNING *',
                [status, id]
            );
            return result.rows[0] || null;
        } catch (error) {
            logger.error(`AlertRequestMap.updateStatus error: ${error.message}`);
            throw error;
        }
    }

    /**
     * [ARCH-114] Inventory of every uk_request_number we've stored.
     *
     * Used by UK's reconciliation worker to set-diff against their local
     * `requests` table and replay any missing rows via webhook. See
     * docs/audit/2026-05-24-ARCH-114-uk-requests-inventory-spec.md for
     * the contract and rationale.
     *
     * Returns terminal AND non-terminal rows — filtering out resolved
     * entries would create false replay events. Mappings without a
     * uk_request_number (sender race / failed sends) are excluded.
     *
     * @param {object} [opts]
     * @param {number} [opts.limit=5000] - Soft cap, hard maximum 10000.
     */
    static async listInventory({ limit = 5000 } = {}) {
        const safeLimit = Math.min(Math.max(parseInt(limit, 10) || 5000, 1), 10000);
        try {
            const result = await db.query(
                `SELECT uk_request_number,
                        status,
                        building_external_id,
                        updated_at
                 FROM alert_request_map
                 WHERE uk_request_number IS NOT NULL
                 ORDER BY updated_at DESC
                 LIMIT $1`,
                [safeLimit]
            );
            return { rows: result.rows, limit: safeLimit };
        } catch (error) {
            logger.error(`AlertRequestMap.listInventory error: ${error.message}`);
            throw error;
        }
    }

    static async areAllTerminal(alertId) {
        try {
            const result = await db.query(
                `SELECT COUNT(*) as total,
                        COUNT(*) FILTER (WHERE status IN ('resolved', 'cancelled')) as terminal
                 FROM alert_request_map
                 WHERE infrasafe_alert_id = $1`,
                [alertId]
            );
            const row = result.rows[0];
            if (!row || parseInt(row.total) === 0) return false;
            return parseInt(row.terminal) === parseInt(row.total);
        } catch (error) {
            logger.error(`AlertRequestMap.areAllTerminal error: ${error.message}`);
            throw error;
        }
    }
}

module.exports = AlertRequestMap;
